version: "3.2"
services:

 redis:
    image: "redis:alpine"

    command: redis-server --requirepass password1
    container_name: redis
    ports:
     - "6379:6379"

    volumes:
     - e:\Volumes\redis\redis-data:/var/lib/redis
     - e:\Volumes\redis\redis.conf:/usr/local/etc/redis/redis.conf

    environment:
     - REDIS_REPLICATION_MODE=master

    networks:
      - specical-links 

networks: 
  specical-links: 
    driver: bridge
    external: true