version: '3.9'

services:
  mongodb:
    image: mongo:lastest
    ports:
      - 27017:27017
    volumes:
      - e:\volume\mongo\data:/data/db
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=S3cret